#!/bin/sh
export USE_CCACHE=1
export CCACHE_EXEC=/usr/bin/ccache

set -e

help() {
    printf "\nUsage: ${0} [OPTIONS]

    Available options:
        - build
        - clean\n"
}

if [ "${1}" = "build" ]; then
    echo ""; read -p "Specify the branch to build for (e.g. eleven): " branch
    read -p "Specify the device codename to build for (e.g. lancelot): " device_codename

    if [ -z "${branch}" ] || [ -z "${device_codename}" ]; then
        echo "Branch or device codename not specified, try again"
        exit
    fi

    echo ""; echo "Installing dependencies..."
    if [ ! -x /usr/bin/git ] || [ ! -x /usr/bin/yay ]; then
        pacman -S git --needed --noconfirm
        git clone https://aur.archlinux.org/yay-git.git; makepkg -csi
        yay -S aosp-devel --needed --noconfirm
        else
            yay -S aosp-devel --needed --noconfirm
    fi

    if [ ! -d "pixel" ]; then
        echo ""; echo "Creating pixel folder..."; mkdir -p pixel
    fi 

    echo ""; echo "Changing directory to lineage pixel..."; cd pixel

    if [ ! -d ".repo/local_manifests" ]; then
        echo ""; echo "Creating directory '.repo/local_manifests'..."
        mkdir -p ".repo/local_manifests"
    fi

    case "${branch}" in
        "eleven"|"eleven-plus")
            branch="${branch}"
        ;;

        *)
            echo ""; echo ":: ERROR: ${branch}: Invalid or unknown branch"
            exit 1
        ;;
    esac

    case "${device_codename}" in
        "lava"|"merlin")
            if [ ! -f ".repo/local_manifests/redmi-mt6768.xml" ]; then
                echo ""; echo "Fetching manifest file for ${device_codename} device..."
                curl -sL https://raw.githubusercontent.com/Redmi-MT6768/local_manifests/master/eleven.xml -o ".repo/local_manifests/redmi-mt6768.xml" --create-dirs
            fi
        ;;

        *)
            echo ""; echo ":: ERROR: ${device_codename}: Invalid or unknown device"
            echo "This script only supports MediaTek devices from Xiaomi for now."
            exit 1
        ;;
    esac

    if [ -x "/usr/bin/repo" ]; then
        echo ""; echo "Initializing PixelExperience repository..."
        repo init -u https://github.com/PixelExperience/manifest -b "${branch}"
    fi

    echo ""; echo "Downloading PixelExperience source tree..."
    repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    echo ""; echo "Setting up environment..."
    . build/envsetup.sh; ccache -M 50G

    echo ""; echo "Extracting propietary blobs for '${device_codename}'..."
    for i in device/xiaomi/${device_codename}/*.sh; do
        chmod +x "${i}"
    done
    #sudo bash device/xiaomi/${device_codename}/extract-files.sh

    echo ""; echo "Building 'aosp_${device_codename}-userdebug'..."
    lunch aosp_${device_codename}-userdebug; mka bacon -j$(nproc --all)
    exit
    elif [ "${1}" = "clean" ]; then
        rm -rfv pixel
        exit
    else
        help
fi
