#!/bin/sh
export USE_CCACHE=1
export CCACHE_EXEC=/usr/bin/ccache

set -e

help() {
    printf "\nUsage: ${0} [OPTIONS]

Options:
    --branch,-b     Set the branch to be used
    --brand,-B      Set the device's brand to be used
    --device,-d     Set the device's codename to be used
    --clean,-c      Clean and remove the building directory
    --help,-h\n"
}

[ -z "${1}" ] && help && exit

while [ $# -gt 0 ]; do
    case "${1}" in
        --branch|-b)
            shift
            export branch="${1}"
        ;;

        --brand|-B)
            shift
            export device_brand="${1}"
        ;;

        --device|-d)
            shift
            export device_codename="${1}"
        ;;

        --clean|-c)
            [ -d "pixel" ] && \
                rm -rfv "pixel"
            exit
        ;;

        --help|-h)
            help
            exit
        ;;

        *)
            help
            exit
        ;;
    esac
    shift
done

if [ -z "${branch}" ] || [ -z "${device_codename}" ]; then
    echo "No branch or device specified"
    exit
fi

echo "Installing dependencies..." && \
    [ ! -x "$(which git)" ] && pacman -Syu git --needed --noconfirm

[ ! -x "$(which yay)" ] && \
    git clone https://aur.archlinux.org/yay.git > /dev/null 2>&1 && \
    cd yay && makepkg -csi > /dev/null 2>&1 && \
    yay -Syu aosp-devel --needed --noconfirm > /dev/null 2>&1 || \
    yay -Syu aosp-devel --needed --noconfirm > /dev/null 2>&1

[ ! -d "pixel" ] && \
    echo "Creating pixel folder..." && \
    mkdir -p pixel && \
    echo "Changing directory to pixel folder..." && \
    cd pixel || \
    echo "Changing directory to pixel folder..." && \
    cd "pixel"

[ ! -d ".repo/local_manifests" ] && \
    echo "Creating directory '.repo/local_manifests'..." && \
        mkdir -p ".repo/local_manifests"

[ -x "$(which repo)" ] && \
    echo "Initializing PixelExperience repository..." && \
    repo init -u https://github.com/PixelExperience/manifest -b "${branch}"

echo "Downloading PixelExperience source tree..." && \
    repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

echo "Setting up environment..." && \
    . build/envsetup.sh && \
    ccache -M 50G

echo "Building 'aosp_${device_codename}-userdebug'..."  && \
    breakfast ${device_codename} && \
    make idegen && \
    lunch aosp_${device_codename}-userdebug && \
    mka bacon -j$(nproc --all)
